# References:
# - https://github.com/slockit/in3/blob/master/docs/getting_started.md#registering-a-own-in3-node
version: '2'
services:
  # add tor server and expose onion address

  incubed-server:
    image: slockit/in3-server:latest
    volumes:
    - $PWD:/secure                                          # directory where the private key is stored
    expose:                                                 # swap `ports` for `expose` since publishing a
                                                            # Tor service and we do not want to map any ports
                                                            # to the host machine. The Incubed server will
                                                            # therefore base inaccessible outside of the
                                                            # Tor network
                                                            # Reference: https://randywestergren.com/running-a-hidden-tor-service-with-docker-compose/
    - 8500/tcp                                              # open the port 8500 to be accessed by public
    - 9050/tcp                                              # open the socket port 9050 (see file torrc)
    command:
    # Generated Account
    # private key: b9bcef71ad544a209ae348af0306ad776e3a0842496e41d2410fcd5996856c11
    - --privateKey=/secure/keystore.json                    # internal path to the key
    - --privateKeyPassphrase=p                              # passphrase to unlock the key
    - --chain=0x5                                           # chain (Görli)
    - --rpcUrl=http://incubed-parity:8545                   # url of the goerli-client
    - --registry=0x85613723dB1Bc29f332A37EeF10b61F8a4225c7e # url of the incubed-registry 
    - --autoRegistry-url=http://in3.server:8500             # check or register this node for this url
    - --autoRegistry-deposit=2                              # deposit to use when registering

  incubed-parity:
    image: parity/parity:v2.5.0
    # image: parity/parity:stable                             # https://hub.docker.com/r/parity/parity/tags
    # image: slockit/parity-in3:v2.2                          # parity-image with the getProof-function implemented
    # image: slockit/parity-in3:latest
    # image: slockit/parity-in3:v2.3
    command:
    - --chain=0x5                                           # chain (Görli)
    - --auto-update=none                                    # do not automaticly update the client
    - --pruning=archive 
    - --pruning-memory=30000                             # limit storage

    # TODO - replace with manual Dockerfile that runs v2.5 of Parity Ethereum since that release supports Görli

  # incubed-geth:
  #   image: ethereum/client-go

  tor:                                                      # References: https://randywestergren.com/running-a-hidden-tor-service-with-docker-compose/
    build: tor-hidden-service/
    links:
      - incubed-server
      - incubed-parity
      # - incubed-geth
